name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:      

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  

      - name: Update all submodules
        run: |
          git submodule update --remote --merge  # 拉取所有子模块的最新提交
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: update submodules to latest"
          git push